// dashboard-solid/src/pages/PlanDetailPage.tsx
import { createSignal, Show, createResource, For } from "solid-js";
import { useParams, A } from "@solidjs/router";
import { 
  ArrowLeft, 
  Bot, 
  Clock, 
  GitBranch, 
  ListChecks, 
  Activity, 
  Target,
  Terminal,
  Database,
  Users,
  Layers,
  Shield,
  MessageSquare,
  Play,
  CheckCircle2
} from 'lucide-solid';
import { fetchPlan } from "../lib/api";
import { StepList, Step } from "../components/plan/StepList";
import { clsx } from "clsx";
import { twMerge } from "tailwind-merge";

function cn(...inputs: any[]) {
  return twMerge(clsx(inputs));
}

export default function PlanDetailPage() {
  const params = useParams();
  const workspaceId = () => params.workspaceId;
  const planId = () => params.planId;

  const [plan] = createResource(
    () => ({ workspaceId: workspaceId(), planId: planId() }),
    async ({ workspaceId, planId }) => {
      if (!workspaceId || !planId) return null;
      const res = await fetchPlan(workspaceId, planId);
      return res.data;
    }
  );

  const steps = () => (plan()?.steps || []) as Step[];
  const progress = () => {
    const s = steps();
    if (s.length === 0) return 0;
    const done = s.filter(st => st.status === 'done').length;
    return (done / s.length) * 100;
  };

  return (
    <div class="space-y-6">
      {/* Breadcrumbs */}
      <div class="flex items-center gap-4">
        <A href={`/workspace/${workspaceId()}`} class="p-2 hover:bg-gray-800 rounded-full text-gray-400 hover:text-white transition-colors">
          <ArrowLeft size={20} />
        </A>
        <div class="flex items-center gap-2 text-gray-400 text-sm">
          <A href="/" class="hover:text-white">Dashboard</A>
          <span>/</span>
          <A href={`/workspace/${workspaceId()}`} class="hover:text-white">Workspace</A>
          <span>/</span>
          <span class="text-gray-200 font-medium">Plan</span>
        </div>
      </div>

      <Show when={!plan.loading} fallback={<div class="animate-pulse space-y-6">
        <div class="h-8 bg-gray-800 rounded w-48" />
        <div class="h-64 bg-gray-800 rounded-lg" />
      </div>}>
        {/* Plan Header */}
        <div class="bg-gray-800 p-6 rounded-xl border border-gray-700 shadow-xl">
          <div class="flex flex-col md:flex-row md:items-start justify-between gap-6">
            <div class="space-y-4 flex-1">
              <div class="flex items-center gap-3">
                <span class={cn(
                  "px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider border",
                  plan()?.priority === 'critical' ? "bg-red-500/10 text-red-400 border-red-500/20" :
                  plan()?.priority === 'high' ? "bg-orange-500/10 text-orange-400 border-orange-500/20" :
                  "bg-blue-500/10 text-blue-400 border-blue-500/20"
                )}>
                  {plan()?.priority} Priority
                </span>
                <span class="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider border bg-gray-700 text-gray-300 border-gray-600">
                  {plan()?.category}
                </span>
              </div>
              
              <h1 class="text-3xl font-bold text-white leading-tight">
                {plan()?.title}
              </h1>
              
              <p class="text-gray-400 text-sm max-w-2xl leading-relaxed">
                {plan()?.description}
              </p>

              <div class="flex flex-wrap items-center gap-6 pt-2">
                <div class="flex items-center gap-2 text-gray-400 text-sm">
                  <Clock size={16} />
                  <span>Created {plan()?.created_at ? new Date(plan()!.created_at).toLocaleDateString() : 'N/A'}</span>
                </div>
                <div class="flex items-center gap-2 text-gray-400 text-sm">
                  <Activity size={16} />
                  <span>{plan()?.status}</span>
                </div>
              </div>
            </div>

            <div class="w-full md:w-64 space-y-4">
              <div class="bg-gray-900/50 p-4 rounded-lg border border-gray-700/50">
                <div class="flex items-center justify-between mb-2">
                  <span class="text-xs font-bold text-gray-500 uppercase tracking-wider">Overall Progress</span>
                  <span class="text-sm font-bold text-indigo-400">{Math.round(progress())}%</span>
                </div>
                <div class="w-full h-2 bg-gray-700 rounded-full overflow-hidden">
                  <div 
                    class="h-full bg-indigo-500 rounded-full transition-all duration-700 ease-out" 
                    style={`width: ${progress()}%`}
                  />
                </div>
                <div class="mt-3 flex justify-between text-[10px] text-gray-500 font-mono">
                  <span>{steps().filter(s => s.status === 'done').length} DONE</span>
                  <span>{steps().length} TOTAL</span>
                </div>
              </div>
              
              <button class="w-full py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition-colors text-sm font-bold flex items-center justify-center gap-2 shadow-lg shadow-indigo-900/20">
                <Play size={16} fill="currentColor" />
                Launch Agent
              </button>
            </div>
          </div>
        </div>

        {/* Content Tabs */}
        <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Main Steps List */}
          <div class="lg:col-span-2 space-y-4">
            <div class="flex items-center justify-between">
              <h2 class="text-lg font-bold text-white flex items-center gap-2">
                <ListChecks size={20} class="text-indigo-400" />
                Execution Steps
              </h2>
            </div>
            
            <StepList steps={steps()} />
          </div>

          {/* Sidebar Panels */}
          <div class="space-y-6">
            {/* Goals Panel */}
            <div class="bg-gray-800 rounded-xl border border-gray-700 overflow-hidden">
              <div class="bg-gray-700/30 px-4 py-3 border-b border-gray-700 flex items-center gap-2">
                <Target size={18} class="text-indigo-400" />
                <h3 class="text-sm font-bold text-white uppercase tracking-wider">Plan Goals</h3>
              </div>
              <div class="p-4 space-y-3">
                <For each={plan()?.goals || []}>
                  {(goal) => (
                    <div class="flex items-start gap-3">
                      <div class="mt-1 w-1.5 h-1.5 rounded-full bg-indigo-500 shrink-0" />
                      <p class="text-sm text-gray-300 leading-snug">{goal}</p>
                    </div>
                  )}
                </For>
              </div>
            </div>

            {/* Success Criteria Panel */}
            <div class="bg-gray-800 rounded-xl border border-gray-700 overflow-hidden">
              <div class="bg-gray-700/30 px-4 py-3 border-b border-gray-700 flex items-center gap-2">
                <Shield size={18} class="text-green-400" />
                <h3 class="text-sm font-bold text-white uppercase tracking-wider">Success Criteria</h3>
              </div>
              <div class="p-4 space-y-3">
                <For each={plan()?.success_criteria || []}>
                  {(criteria) => (
                    <div class="flex items-start gap-3">
                      <div class="mt-1">
                        <CheckCircle2 size={14} class="text-green-500" />
                      </div>
                      <p class="text-sm text-gray-300 leading-snug">{criteria}</p>
                    </div>
                  )}
                </For>
              </div>
            </div>
          </div>
        </div>
      </Show>
    </div>
  );
}

// dashboard/src/pages/PlanDetailPage.tsx
import { useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, Clock, GitBranch, ListChecks, FileText, Activity, BarChart, Info, AlertTriangle, MessageSquare } from 'lucide-react';
import { Badge } from '@/components/common/Badge';
import { ProgressBar } from '@/components/common/ProgressBar';
import { StepList } from '@/components/plan/StepList';
import { StepProgress } from '@/components/plan/StepProgress';
import { ResearchNotesViewer } from '@/components/plan/ResearchNotesViewer';
import { AuditLogViewer } from '@/components/plan/AuditLogViewer';
import { ExportReport } from '@/components/plan/ExportReport';
import { PlanActions } from '@/components/plan/PlanActions';
import { AddNoteForm } from '@/components/plan/AddNoteForm';
import { HandoffTimeline } from '@/components/timeline/HandoffTimeline';
import { BallInCourt } from '@/components/timeline/BallInCourt';
import { formatDate, formatRelative } from '@/utils/formatters';
import { categoryColors, priorityColors, priorityIcons, planStatusColors } from '@/utils/colors';
import { cn } from '@/utils/cn';
import type { PlanState, AgentType } from '@/types';

async function fetchPlan(workspaceId: string, planId: string): Promise<PlanState> {
  const res = await fetch(`/api/plans/${workspaceId}/${planId}`);
  if (!res.ok) throw new Error('Failed to fetch plan');
  return res.json();
}

type Tab = 'timeline' | 'steps' | 'research' | 'activity';

export function PlanDetailPage() {
  const { workspaceId, planId } = useParams<{ workspaceId: string; planId: string }>();
  const [activeTab, setActiveTab] = useState<Tab>('timeline');
  const [stepView, setStepView] = useState<'bar' | 'kanban'>('bar');

  const { data: plan, isLoading, error } = useQuery({
    queryKey: ['plan', workspaceId, planId],
    queryFn: () => fetchPlan(workspaceId!, planId!),
    enabled: !!workspaceId && !!planId,
  });

  if (isLoading) {
    return (
      <div className="animate-pulse space-y-6">
        <div className="h-8 bg-slate-700 rounded w-48" />
        <div className="h-48 bg-slate-800 rounded-lg" />
        <div className="h-96 bg-slate-800 rounded-lg" />
      </div>
    );
  }

  if (error || !plan) {
    return (
      <div className="text-center py-12">
        <p className="text-red-400 text-lg">Plan not found</p>
        <Link to={`/workspace/${workspaceId}`} className="text-violet-400 hover:underline mt-2 inline-block">
          Return to workspace
        </Link>
      </div>
    );
  }

  const doneSteps = plan.steps?.filter((s) => s.status === 'done').length || 0;
  const totalSteps = plan.steps?.length || 0;

  // Get current session if agent is active
  const currentSession = plan.current_agent
    ? plan.agent_sessions?.find(
        (s) => s.agent_type === plan.current_agent && !s.completed_at
      )
    : undefined;

  const tabs: { id: Tab; label: string; icon: React.ReactNode }[] = [
    { id: 'timeline', label: 'Timeline', icon: <GitBranch size={16} /> },
    { id: 'steps', label: 'Steps', icon: <ListChecks size={16} /> },
    { id: 'research', label: 'Research', icon: <FileText size={16} /> },
    { id: 'activity', label: 'Activity', icon: <Activity size={16} /> },
  ];

  return (
    <div className="space-y-6">
      {/* Breadcrumb */}
      <Link
        to={`/workspace/${workspaceId}`}
        className="inline-flex items-center gap-2 text-slate-400 hover:text-slate-200 transition-colors"
      >
        <ArrowLeft size={16} />
        Back to Workspace
      </Link>

      {/* Header */}
      <div className="bg-slate-800 border border-slate-700 rounded-lg p-6">
        <div className="flex items-start justify-between mb-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <Badge variant={categoryColors[plan.category]}>{plan.category}</Badge>
              <Badge variant={priorityColors[plan.priority]}>
                {priorityIcons[plan.priority]} {plan.priority}
              </Badge>
              <Badge variant={planStatusColors[plan.status]}>{plan.status}</Badge>
            </div>
            <h1 className="text-2xl font-bold mb-2">{plan.title}</h1>
            <p className="text-slate-400">{plan.description}</p>
          </div>
          <div className="text-right text-sm text-slate-400">
            <div className="flex items-center gap-2 justify-end mb-2">
              <ExportReport 
                workspaceId={workspaceId!} 
                planId={planId!} 
                planTitle={plan.title} 
              />
              <PlanActions
                workspaceId={workspaceId!}
                planId={planId!}
                planTitle={plan.title}
              />
            </div>
            <div className="font-mono mb-1">{plan.id}</div>
            <div className="flex items-center gap-1 justify-end">
              <Clock size={14} />
              Created {formatDate(plan.created_at)}
            </div>
            <div>Updated {formatRelative(plan.updated_at)}</div>
          </div>
        </div>

        {/* Progress */}
        <div className="flex items-center gap-4">
          <span className="text-sm text-slate-400">Progress</span>
          <div className="flex-1 max-w-md">
            <ProgressBar value={doneSteps} max={totalSteps} showLabel />
          </div>
        </div>
      </div>

      {/* Pending Notes */}
      {plan.pending_notes && plan.pending_notes.length > 0 && (
        <div className="bg-slate-800 border-l-4 border-violet-500 rounded-lg p-4">
          <div className="flex items-center gap-2 mb-3">
            <MessageSquare size={18} className="text-violet-400" />
            <h3 className="font-semibold">Pending Notes for Next Agent</h3>
            <Badge variant="violet">{plan.pending_notes.length}</Badge>
          </div>
          <div className="space-y-2">
            {plan.pending_notes.map((note, idx) => (
              <div key={idx} className="bg-slate-900/50 rounded p-3 border border-slate-700">
                <div className="flex items-center gap-2 mb-1">
                  {note.type === 'info' && <Info size={14} className="text-blue-400" />}
                  {note.type === 'warning' && <AlertTriangle size={14} className="text-amber-400" />}
                  {note.type === 'instruction' && <MessageSquare size={14} className="text-violet-400" />}
                  <Badge variant={note.type === 'info' ? 'blue' : note.type === 'warning' ? 'amber' : 'violet'}>
                    {note.type}
                  </Badge>
                  <span className="text-xs text-slate-500">{formatRelative(note.added_at)}</span>
                </div>
                <p className="text-slate-200 text-sm">{note.note}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Ball in Court */}
      <BallInCourt currentAgent={plan.current_agent as AgentType} currentSession={currentSession} />

      {/* Tabs */}
      <div className="border-b border-slate-700">
        <div className="flex gap-1">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={cn(
                'flex items-center gap-2 px-4 py-3 border-b-2 transition-colors',
                activeTab === tab.id
                  ? 'border-violet-500 text-violet-300'
                  : 'border-transparent text-slate-400 hover:text-slate-200'
              )}
            >
              {tab.icon}
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      {/* Tab Content */}
      <div className="bg-slate-800 border border-slate-700 rounded-lg p-6">
        {activeTab === 'timeline' && (
          <HandoffTimeline lineage={plan.lineage || []} sessions={plan.agent_sessions || []} />
        )}
        {activeTab === 'steps' && (
          <div className="space-y-6">
            {/* Add Note Form */}
            <AddNoteForm workspaceId={workspaceId!} planId={planId!} />

            {/* View Toggle */}
            <div className="flex items-center justify-between">
              <h3 className="font-semibold text-lg">Step Progress</h3>
              <div className="flex gap-2">
                <button
                  onClick={() => setStepView('bar')}
                  className={cn(
                    'px-3 py-1.5 rounded-lg text-sm flex items-center gap-2 transition-colors',
                    stepView === 'bar'
                      ? 'bg-violet-500/20 text-violet-300'
                      : 'bg-slate-700 text-slate-400 hover:text-slate-200'
                  )}
                >
                  <BarChart size={14} />
                  Bar
                </button>
                <button
                  onClick={() => setStepView('kanban')}
                  className={cn(
                    'px-3 py-1.5 rounded-lg text-sm flex items-center gap-2 transition-colors',
                    stepView === 'kanban'
                      ? 'bg-violet-500/20 text-violet-300'
                      : 'bg-slate-700 text-slate-400 hover:text-slate-200'
                  )}
                >
                  <ListChecks size={14} />
                  Kanban
                </button>
              </div>
            </div>
            
            {/* Progress Visualization */}
            <StepProgress steps={plan.steps || []} view={stepView} />
            
            {/* Detailed Step List */}
            <div className="border-t border-slate-700 pt-6">
              <h3 className="font-semibold text-lg mb-4">All Steps</h3>
              <StepList 
                steps={plan.steps || []} 
                workspaceId={workspaceId}
                planId={planId}
                editable={true}
              />
            </div>
          </div>
        )}
        {activeTab === 'research' && (
          <ResearchNotesViewer workspaceId={workspaceId!} planId={planId!} />
        )}
        {activeTab === 'activity' && (
          <AuditLogViewer workspaceId={workspaceId!} planId={planId!} />
        )}
      </div>
    </div>
  );
}
