// dashboard-solid/src/App.tsx
import { Route } from "@solidjs/router";
import { lazy } from "solid-js";
import { Layout } from "./components/layout/Layout";

const Dashboard = lazy(() => import("./pages/Dashboard"));
const WorkspacePage = lazy(() => import("./pages/WorkspacePage"));
const PlanDetailPage = lazy(() => import("./pages/PlanDetailPage"));
const MetricsPage = lazy(() => import("./pages/MetricsPage"));

function App() {
  return (
    <Layout>
      <Route path="/" component={Dashboard} />
      <Route path="/workspace/:workspaceId" component={WorkspacePage} />
      <Route path="/workspace/:workspaceId/plan/:planId" component={PlanDetailPage} />
      <Route path="/metrics" component={MetricsPage} />
      {/* 
        Remaining routes from React dashboard:
        - /agents
        - /prompts
        - /instructions
        - /skills
      */}
    </Layout>
  );
}

export default App;

// dashboard/src/App.tsx
import { Routes, Route } from 'react-router-dom';
import { Layout } from './components/layout/Layout';
import { DashboardPage } from './pages/DashboardPage';
import { WorkspacePage } from './pages/WorkspacePage';
import { PlanDetailPage } from './pages/PlanDetailPage';
import { AgentsPage } from './pages/AgentsPage';
import { AgentEditorPage } from './pages/AgentEditorPage';
import { MetricsPage } from './pages/MetricsPage';
import { PromptsPage } from './pages/PromptsPage';
import { InstructionsPage } from './pages/InstructionsPage';
import { useLiveUpdates } from './hooks/useLiveUpdates';
import { useMCPEvents } from './hooks/useMCPEvents';
import { ToastContainer } from './components/common/Toast';
import { ErrorBoundary } from './components/common/ErrorBoundary';

function App() {
  // Enable live updates via WebSocket
  useLiveUpdates();
  
  // Enable MCP event handling with toasts
  useMCPEvents();

  return (
    <ErrorBoundary>
      <Layout>
        <Routes>
          <Route path="/" element={<DashboardPage />} />
          <Route path="/workspace/:workspaceId" element={<WorkspacePage />} />
          <Route path="/workspace/:workspaceId/plan/:planId" element={<PlanDetailPage />} />
          <Route path="/agents" element={<AgentsPage />} />
          <Route path="/agents/:agentId" element={<AgentEditorPage />} />
          <Route path="/prompts" element={<PromptsPage />} />
          <Route path="/instructions" element={<InstructionsPage />} />
          <Route path="/metrics" element={<MetricsPage />} />
        </Routes>
      </Layout>
      <ToastContainer />
    </ErrorBoundary>
  );
}

export default App;
