// dashboard/src/components/layout/Layout.tsx
import { ReactNode, useState } from 'react';
import { Sidebar } from './Sidebar';
import { Header } from './Header';

interface LayoutProps {
  children: ReactNode;
}

export function Layout({ children }: LayoutProps) {
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);

  return (
    <div className="flex h-screen bg-slate-900 text-slate-100">
      {/* Skip to main content link for keyboard navigation */}
      <a
        href="#main-content"
        className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:px-4 focus:py-2 focus:bg-blue-600 focus:text-white focus:rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
      >
        Skip to main content
      </a>
      
      <Sidebar collapsed={sidebarCollapsed} onToggle={() => setSidebarCollapsed(!sidebarCollapsed)} />
      <div className="flex flex-col flex-1 overflow-hidden">
        <Header />
        <main 
          id="main-content"
          className="flex-1 overflow-auto p-6 scrollbar-thin"
          role="main"
          tabIndex={-1}
        >
          {children}
        </main>
      </div>
    </div>
  );
}

// dashboard-solid/src/components/layout/Layout.tsx
import { createSignal, JSX } from "solid-js";
import { Sidebar } from "./Sidebar";
import { Header } from "./Header";

interface LayoutProps {
  children?: JSX.Element;
}

export function Layout(props: LayoutProps) {
  const [sidebarCollapsed, setSidebarCollapsed] = createSignal(false);

  return (
    <div class="flex h-screen bg-gray-900 text-gray-100 overflow-hidden font-sans">
      <Sidebar 
        collapsed={sidebarCollapsed()} 
        onToggle={() => setSidebarCollapsed(!sidebarCollapsed())} 
      />
      
      <div class="flex flex-col flex-1 overflow-hidden">
        <Header />
        
        <main 
          id="main-content"
          class="flex-1 overflow-auto p-6 scrollbar-thin scrollbar-thumb-gray-700 scrollbar-track-transparent"
        >
          {props.children}
        </main>
      </div>
    </div>
  );
}
